# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install lxml
    - name: Test
      run: |
        pip list
    - name: download tools.py
      shell: python
      run: |
        # -*- coding: utf-8 -*-
        import requests,os
        
        def reload_module(_module, path=None, raise_=False):
          if path:
            import sys
            sys_path_temp = list(sys.path)
            sys.path.insert(0, path)
          try:
            import importlib
            module_ = importlib.import_module(".", _module)
            _module_ = importlib.reload(module_)
            return _module_
          except (ImportError, ModuleNotFoundError) as err:
            if path:
              sys.path = sys_path_temp
            if raise_:
              raise err
            return None
      
        res = requests.get('https://github.com/adhu2018/tools/raw/master/tools.py')
        with open("{}tools.py".format(os.environ["FILE_PATH"]), 'wb') as f:
          f.write(res.content)
        tools = reload_module("tools", path=os.environ["FILE_PATH"])
        result = tools.meiriyiwen().print(False)
        with open("{}result.txt".format(os.environ["FILE_PATH"]), 'wb') as f:
          f.write(res.content)
      env:
        FILE_PATH: ${{ github.workspace }}/.github/
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{secrets.EMAIL_NAME}}
        password: ${{secrets.EMAIL_PASSWORD}}
        subject: Github Actions job result
        body: file://.github/result.txt
        to: qa455355@163.com
        from: GitHub Actions
      env:
        FILE_PATH: ${{ github.workspace }}/.github/
